name: Docker

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Build Docker image and push to registry
        run: | 
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg NETWORK=regtest \
            --tag ghcr.io/swapmarket/web-app:latest \
            --output "type=registry" \
            .
